language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t feridqelenderli/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true feridqelenderli/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-043393912804"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
